# Generated by Django 4.1.3 on 2022-11-22 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        ('menu', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='my_menu',
            field=models.ManyToManyField(blank=True, null=True, to='menu.menu'),
        ),
        migrations.AddField(
            model_name='user',
            name='my_store',
            field=models.ManyToManyField(blank=True, null=True, to='restaurants.restaurant'),
        ),
    ]
