# Generated by Django 4.1.3 on 2022-11-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('winter', 'winter'), ('summer', 'summer'), ('spring', 'spring'), ('fall', 'fall')], max_length=20)),
                ('location_type', models.CharField(max_length=20, verbose_name={('winter', 'winter'), ('summer', 'summer'), ('spring', 'spring'), ('fall', 'fall')})),
                ('explain', models.CharField(max_length=500)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
            ],
        ),
    ]
