# Generated by Django 4.1.3 on 2022-11-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_restaurant_location_type_alter_restaurant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='location_type',
            field=models.CharField(choices=[('summer', 'summdddd'), ('winter', 'winter'), ('spring', 'spring'), ('fall', 'fall')], max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='type',
            field=models.CharField(choices=[('중식', '중식'), ('winter', 'winter'), ('한식', '한식'), ('fall', 'fall')], max_length=20),
        ),
    ]
