# Generated by Django 4.1.3 on 2022-11-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_alter_restaurant_location_type_alter_restaurant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='location_type',
            field=models.CharField(choices=[('winter', 'winter'), ('spring', 'spring'), ('fall', 'fall'), ('summer', 'summdddd')], max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='type',
            field=models.CharField(choices=[('일식', '일식'), ('chinese', '중식'), ('korean', '한식'), ('양식', '양식')], max_length=20),
        ),
    ]
