# Generated by Django 4.1.3 on 2022-11-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_alter_restaurant_location_type_alter_restaurant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='location_type',
            field=models.CharField(choices=[('sinchon', '신촌'), ('south_gate', '남문'), ('back_gate', '후문'), ('daeheung', '대흥'), ('front_gate', '정문')], max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='type',
            field=models.CharField(choices=[('western', '양식'), ('chinese', '중식'), ('japanese', '일식'), ('korean', '한식')], max_length=20),
        ),
    ]
