# Generated by Django 4.1.3 on 2022-11-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_restaurant_store_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='location_type',
            field=models.CharField(choices=[('sinchon', '신촌'), ('back_gate', '후문'), ('south_gate', '남문'), ('front_gate', '정문'), ('daeheung', '대흥')], max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='type',
            field=models.CharField(choices=[('korean', '한식'), ('western', '양식'), ('chinese', '중식'), ('japanese', '일식')], max_length=20),
        ),
    ]
