# Generated by Django 4.1.3 on 2022-11-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_alter_restaurant_location_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='location_type',
            field=models.CharField(choices=[('후문', '후문'), ('정문', '정문'), ('남문', '남문'), ('대흥', '대흥'), ('신촌', '신촌')], max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='type',
            field=models.CharField(choices=[('양식', '양식'), ('일식', '일식'), ('한식', '한식'), ('중식', '중식')], max_length=20),
        ),
    ]
