# Generated by Django 4.1.3 on 2022-11-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_alter_restaurant_location_type_alter_restaurant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='location_type',
            field=models.CharField(choices=[('신촌', '신촌'), ('대흥', '대흥'), ('정문', '정문'), ('남문', '남문'), ('후문', '후문')], max_length=20),
        ),
    ]
