# Generated by Django 4.1.3 on 2022-11-20 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_alter_restaurant_location_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='location_type',
            field=models.CharField(choices=[('후문', '후문'), ('대흥', '대흥'), ('정문', '정문'), ('신촌', '신촌'), ('남문', '남문')], max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='type',
            field=models.CharField(choices=[('중식', '중식'), ('양식', '양식'), ('한식', '한식'), ('일식', '일식')], max_length=20),
        ),
    ]
