# Generated by Django 4.1.3 on 2022-11-22 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0017_alter_restaurant_location_type_alter_restaurant_type'),
        ('restaurants', '0017_locationcategory_typecategory_and_more'),
    ]

    operations = [
    ]
