# Generated by Django 4.1.3 on 2022-11-22 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0018_merge_20221122_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='location_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.locationcategory'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurants.typecategory'),
        ),
    ]
