# Generated by Django 4.1.3 on 2022-11-20 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='sale',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.sale'),
        ),
    ]
