# Generated by Django 4.1.3 on 2022-11-20 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.sale'),
        ),
    ]
