# Generated by Django 4.1.3 on 2022-11-20 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_alter_restaurant_location_type_alter_restaurant_type'),
        ('menu', '0003_alter_menu_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(db_column='store_name', on_delete=django.db.models.deletion.CASCADE, to='restaurants.restaurant'),
        ),
    ]
